import { IMember } from "./IMember";

export interface IApiClass {
  ClassId: number;
  NamespaceId: number;
  ComponentId?: number;
  ClassName: string;
  Declaration: string;
  Documentation: string;
  Description: string;
  AppearedInVersion: string;
  DeprecatedInVersion: string;
  DisappearedInVersion: string;
  IsDeprecated: boolean;
  DeprecationMessage: string;
  DocumentationId?: number;
  PendingDescription: string;
  FullName: string;
  IsAbstract: boolean;
  IsAnsiClass: boolean;
  IsArray: boolean;
  IsAutoClass: boolean;
  IsAutoLayout: boolean;
  IsBeforeFieldInit: boolean;
  IsByReference: boolean;
  IsClass: boolean;
  IsDefinition: boolean;
  IsEnum: boolean;
  IsExplicitLayout: boolean;
  IsFunctionPointer: boolean;
  IsGenericInstance: boolean;
  IsGenericParameter: boolean;
  IsImport: boolean;
  IsInterface: boolean;
  IsNested: boolean;
  IsNestedAssembly: boolean;
  IsNestedPrivate: boolean;
  IsNestedPublic: boolean;
  IsNotPublic: boolean;
  CreatedByUserID: number;
  CreatedOnDate: Date;
  LastModifiedByUserID: number;
  LastModifiedOnDate: Date;
  CreatedByUserDisplayName: string;
  LastModifiedByUserDisplayName: string;
  DocumentationContents: string;
  NamespaceName: string;
  FullQualifier: string;
  ModuleId: number;
  ComponentName: string;
  LatestVersion: string;
  MemberCount?: number;
  CreatedByUserID: number;
  CreatedOnDate: Date;
  LastModifiedByUserID: number;
  LastModifiedOnDate: Date;
  Members?: IMember[];
}

export class ApiClass implements IApiClass {
  ClassId: number;
  NamespaceId: number;
  ComponentId?: number;
  ClassName: string;
  Declaration: string;
  Documentation: string;
  Description: string;
  AppearedInVersion: string;
  DeprecatedInVersion: string;
  DisappearedInVersion: string;
  IsDeprecated: boolean;
  DeprecationMessage: string;
  DocumentationId?: number;
  PendingDescription: string;
  FullName: string;
  IsAbstract: boolean;
  IsAnsiClass: boolean;
  IsArray: boolean;
  IsAutoClass: boolean;
  IsAutoLayout: boolean;
  IsBeforeFieldInit: boolean;
  IsByReference: boolean;
  IsClass: boolean;
  IsDefinition: boolean;
  IsEnum: boolean;
  IsExplicitLayout: boolean;
  IsFunctionPointer: boolean;
  IsGenericInstance: boolean;
  IsGenericParameter: boolean;
  IsImport: boolean;
  IsInterface: boolean;
  IsNested: boolean;
  IsNestedAssembly: boolean;
  IsNestedPrivate: boolean;
  IsNestedPublic: boolean;
  IsNotPublic: boolean;
  CreatedByUserID: number;
  CreatedOnDate: Date;
  LastModifiedByUserID: number;
  LastModifiedOnDate: Date;
  CreatedByUserDisplayName: string;
  LastModifiedByUserDisplayName: string;
  DocumentationContents: string;
  NamespaceName: string;
  FullQualifier: string;
  ModuleId: number;
  ComponentName: string;
  LatestVersion: string;
  MemberCount?: number;
  CreatedByUserID: number;
  CreatedOnDate: Date;
  LastModifiedByUserID: number;
  LastModifiedOnDate: Date;
  Members?: IMember[];
  constructor() {
    this.ClassId = -1;
    this.NamespaceId = -1;
    this.ClassName = "";
    this.AppearedInVersion = "";
    this.IsDeprecated = false;
  this.FullName = "";
  this.IsAbstract = false;
  this.IsAnsiClass = false;
  this.IsArray = false;
  this.IsAutoClass = false;
  this.IsAutoLayout = false;
  this.IsBeforeFieldInit = false;
  this.IsByReference = false;
  this.IsClass = false;
  this.IsDefinition = false;
  this.IsEnum = false;
  this.IsExplicitLayout = false;
  this.IsFunctionPointer = false;
  this.IsGenericInstance = false;
  this.IsGenericParameter = false;
  this.IsImport = false;
  this.IsInterface = false;
  this.IsNested = false;
  this.IsNestedAssembly = false;
  this.IsNestedPrivate = false;
  this.IsNestedPublic = false;
  this.IsNotPublic = false;
  this.CreatedByUserID = -1;
  this.CreatedOnDate = new Date();
  this.LastModifiedByUserID = -1;
  this.LastModifiedOnDate = new Date();
    this.NamespaceName = "";
  this.FullQualifier = "";
  this.ModuleId = -1;
    this.ComponentName = "";
    this.LatestVersion = "";
  }
}

